# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

ENV PORT=3000

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . ./

# Expose the port your Express app is listening on (change 3000 if needed)
# docker app communicates with outside world by this port
EXPOSE $PORT

# Command to start your Node.js app
CMD ["npm", "start"]
